import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh-cn' | 'en-us' | 'th-th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  'zh-cn': {
    // Common
    'common.logout': '登出',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.search': '搜索',
    'common.loading': '加载中...',
    'common.saving': '保存中...',
    'common.success': '成功',
    'common.error': '错误',
    'common.confirm': '确认',
    'common.welcome': '欢迎',
    'common.chinese': '中文',
    'common.english': '英文',
    'common.thai': '泰文',
    
    // Navigation
    'nav.stores': '门店管理',
    'nav.campaigns': '活动管理',
    'nav.dashboard': '数据面板',
    
    // Login
    'login.title': '管理后台登录',
    'login.email': '邮箱',
    'login.password': '密码',
    'login.submit': '登录',
    'login.emailPlaceholder': '请输入邮箱',
    'login.passwordPlaceholder': '请输入密码',
    
    // Stores
    'stores.title': '门店管理',
    'stores.addStore': '新建门店',
    'stores.allStores': '所有门店',
    'stores.image': '图片',
    'stores.noImage': '无图片',
    'stores.name': '名称',
    'stores.brand': '品牌',
    'stores.city': '城市',
    'stores.address': '地址',
    'stores.phone': '电话',
    'stores.latitude': '纬度',
    'stores.longitude': '经度',
    'stores.imageUrl': '图片网址',
    'stores.rating': '评分',
    'stores.status': '状态',
    'stores.actions': '操作',
    'stores.active': '启用',
    'stores.inactive': '禁用',
    'stores.createTitle': '新建门店',
    'stores.editTitle': '编辑门店',
    'stores.deleteConfirm': '确定要删除此门店吗？',
    'stores.createSuccess': '门店创建成功',
    'stores.updateSuccess': '门店更新成功',
    'stores.deleteSuccess': '门店删除成功',
    'stores.createError': '创建门店失败',
    'stores.updateError': '更新门店失败',
    'stores.deleteError': '删除门店失败',
    'stores.noData': '暂无门店数据',
    'stores.searchAddress': 'Google地址搜索',
    'stores.searchPlaceholder': '搜索地址...',
    'stores.typeToSearch': '输入地址开始搜索',
    'stores.searchHelp': '使用Google地图搜索自动填充门店信息（名称、地址、经纬度、评分等）',
    'stores.noResults': '未找到相关地址',
    'stores.placeSelected': '地址信息已自动填充',
    'stores.placeDetailsError': '获取地址详情失败',
    
    // Campaigns
    'campaigns.title': '活动管理',
    'campaigns.createNew': '新建活动',
    'campaigns.addCampaign': '新建活动',
    'campaigns.allCampaigns': '所有活动',
    'campaigns.campaignTitle': '标题',
    'campaigns.couponType': '券类型',
    'campaigns.couponValue': '券值',
    'campaigns.startTime': '开始时间',
    'campaigns.endTime': '结束时间',
    'campaigns.startDate': '开始日期',
    'campaigns.endDate': '结束日期',
    'campaigns.status': '状态',
    'campaigns.actions': '操作',
    'campaigns.active': '启用',
    'campaigns.inactive': '禁用',
    'campaigns.createTitle': '新建活动',
    'campaigns.editTitle': '编辑活动',
    'campaigns.editCampaign': '编辑活动',
    'campaigns.deleteConfirm': '确定要删除此活动吗？',
    'campaigns.createSuccess': '活动创建成功',
    'campaigns.updateSuccess': '活动更新成功',
    'campaigns.deleteSuccess': '活动删除成功',
    'campaigns.createError': '创建活动失败',
    'campaigns.updateError': '更新活动失败',
    'campaigns.deleteError': '删除活动失败',
    'campaigns.noData': '暂无活动数据',
    'campaigns.noCampaigns': '暂无活动',
    'campaigns.manageStores': '门店关联管理',
    'campaigns.autoTranslate': 'AI自动翻译',
    'campaigns.translating': 'AI翻译中...',
    'campaigns.translateSuccess': 'AI翻译完成',
    'campaigns.translateError': 'AI翻译失败',
    'campaigns.storesUpdateSuccess': '门店关联更新成功',
    'campaigns.storesUpdateError': '门店关联更新失败',
    'campaigns.basicInfo': '基本信息',
    'campaigns.description': '描述',
    'campaigns.titleLang': '标题主语言',
    'campaigns.multiLanguageContent': '多语言内容（可选）',
    'campaigns.titleChinese': '中文标题',
    'campaigns.titleEnglish': '英文标题',
    'campaigns.titleThai': '泰文标题',
    'campaigns.descriptionChinese': '中文描述',
    'campaigns.descriptionEnglish': '英文描述',
    'campaigns.descriptionThai': '泰文描述',
    'campaigns.couponSettings': '券设置',
    'campaigns.maxPerUser': '每人限领',
    'campaigns.maxTotal': '总库存（留空=无限）',
    'campaigns.enableCampaign': '启用活动',
    'campaigns.finalPrice': '特价',
    'campaigns.giftCard': '礼品卡',
    'campaigns.cashVoucher': '现金券',
    'campaigns.fullReduction': '满减',
    'campaigns.percentageOff': '折扣',
    
    // Campaign Form
    'campaignForm.basicInfo': '基本信息',
    'campaignForm.titleLang': '标题主语言',
    'campaignForm.title': '标题',
    'campaignForm.description': '描述',
    'campaignForm.multiLang': '多语言内容（可选）',
    'campaignForm.titleZh': '中文标题',
    'campaignForm.titleEn': '英文标题',
    'campaignForm.titleTh': '泰文标题',
    'campaignForm.descriptionZh': '中文描述',
    'campaignForm.descriptionEn': '英文描述',
    'campaignForm.descriptionTh': '泰文描述',
    'campaignForm.couponSettings': '券设置',
    'campaignForm.discountType': '券类型',
    'campaignForm.couponValue': '券值',
    'campaignForm.startAt': '开始时间',
    'campaignForm.endAt': '结束时间',
    'campaignForm.maxPerUser': '每人限领',
    'campaignForm.maxTotal': '总库存（留空=无限）',
    'campaignForm.isActive': '启用活动',
    
    // Discount Types
    'discountType.final_price': '特价',
    'discountType.gift_card': '礼品卡',
    'discountType.cash_voucher': '现金券',
    'discountType.full_reduction': '满减',
    'discountType.percentage_off': '折扣',
    
    // Languages
    'language.zh-cn': '中文',
    'language.en-us': 'English',
    'language.th-th': 'ไทย',
  },
  'en-us': {
    // Common
    'common.logout': 'Logout',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.saving': 'Saving...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.confirm': 'Confirm',
    'common.welcome': 'Welcome',
    'common.chinese': 'Chinese',
    'common.english': 'English',
    'common.thai': 'Thai',
    
    // Navigation
    'nav.stores': 'Stores',
    'nav.campaigns': 'Campaigns',
    'nav.dashboard': 'Dashboard',
    
    // Login
    'login.title': 'Admin Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.emailPlaceholder': 'Enter email',
    'login.passwordPlaceholder': 'Enter password',
    
    // Stores
    'stores.title': 'Stores Management',
    'stores.addStore': 'Add Store',
    'stores.allStores': 'All Stores',
    'stores.image': 'Image',
    'stores.noImage': 'No Image',
    'stores.name': 'Name',
    'stores.brand': 'Brand',
    'stores.city': 'City',
    'stores.address': 'Address',
    'stores.phone': 'Phone',
    'stores.latitude': 'Latitude',
    'stores.longitude': 'Longitude',
    'stores.imageUrl': 'Image URL',
    'stores.rating': 'Rating',
    'stores.status': 'Status',
    'stores.actions': 'Actions',
    'stores.active': 'Active',
    'stores.inactive': 'Inactive',
    'stores.createTitle': 'Create Store',
    'stores.editTitle': 'Edit Store',
    'stores.deleteConfirm': 'Are you sure you want to delete this store?',
    'stores.createSuccess': 'Store created successfully',
    'stores.updateSuccess': 'Store updated successfully',
    'stores.deleteSuccess': 'Store deleted successfully',
    'stores.createError': 'Failed to create store',
    'stores.updateError': 'Failed to update store',
    'stores.deleteError': 'Failed to delete store',
    'stores.noData': 'No stores available',
    'stores.searchAddress': 'Google Address Search',
    'stores.searchPlaceholder': 'Search address...',
    'stores.typeToSearch': 'Type to search address',
    'stores.searchHelp': 'Use Google Maps to auto-fill store info (name, address, coordinates, rating, etc.)',
    'stores.noResults': 'No addresses found',
    'stores.placeSelected': 'Address info auto-filled',
    'stores.placeDetailsError': 'Failed to get place details',
    
    // Campaigns
    'campaigns.title': 'Campaigns Management',
    'campaigns.createNew': 'Create Campaign',
    'campaigns.addCampaign': 'Add Campaign',
    'campaigns.allCampaigns': 'All Campaigns',
    'campaigns.campaignTitle': 'Title',
    'campaigns.couponType': 'Type',
    'campaigns.couponValue': 'Value',
    'campaigns.startTime': 'Start Time',
    'campaigns.endTime': 'End Time',
    'campaigns.startDate': 'Start Date',
    'campaigns.endDate': 'End Date',
    'campaigns.status': 'Status',
    'campaigns.actions': 'Actions',
    'campaigns.active': 'Active',
    'campaigns.inactive': 'Inactive',
    'campaigns.createTitle': 'Create Campaign',
    'campaigns.editTitle': 'Edit Campaign',
    'campaigns.editCampaign': 'Edit Campaign',
    'campaigns.deleteConfirm': 'Are you sure you want to delete this campaign?',
    'campaigns.createSuccess': 'Campaign created successfully',
    'campaigns.updateSuccess': 'Campaign updated successfully',
    'campaigns.deleteSuccess': 'Campaign deleted successfully',
    'campaigns.createError': 'Failed to create campaign',
    'campaigns.updateError': 'Failed to update campaign',
    'campaigns.deleteError': 'Failed to delete campaign',
    'campaigns.noData': 'No campaigns available',
    'campaigns.noCampaigns': 'No campaigns',
    'campaigns.manageStores': 'Manage Store Association',
    'campaigns.autoTranslate': 'Auto Translate (AI)',
    'campaigns.translating': 'Translating...',
    'campaigns.translateSuccess': 'Translation completed',
    'campaigns.translateError': 'Translation failed',
    'campaigns.storesUpdateSuccess': 'Store association updated successfully',
    'campaigns.storesUpdateError': 'Failed to update store association',
    'campaigns.basicInfo': 'Basic Information',
    'campaigns.description': 'Description',
    'campaigns.titleLang': 'Title Language',
    'campaigns.multiLanguageContent': 'Multi-language Content (Optional)',
    'campaigns.titleChinese': 'Chinese Title',
    'campaigns.titleEnglish': 'English Title',
    'campaigns.titleThai': 'Thai Title',
    'campaigns.descriptionChinese': 'Chinese Description',
    'campaigns.descriptionEnglish': 'English Description',
    'campaigns.descriptionThai': 'Thai Description',
    'campaigns.couponSettings': 'Coupon Settings',
    'campaigns.maxPerUser': 'Max Per User',
    'campaigns.maxTotal': 'Total Stock (Empty = Unlimited)',
    'campaigns.enableCampaign': 'Enable Campaign',
    'campaigns.finalPrice': 'Final Price',
    'campaigns.giftCard': 'Gift Card',
    'campaigns.cashVoucher': 'Cash Voucher',
    'campaigns.fullReduction': 'Full Reduction',
    'campaigns.percentageOff': 'Percentage Off',
    
    // Campaign Form
    'campaignForm.basicInfo': 'Basic Information',
    'campaignForm.titleLang': 'Title Language',
    'campaignForm.title': 'Title',
    'campaignForm.description': 'Description',
    'campaignForm.multiLang': 'Multi-language Content (Optional)',
    'campaignForm.titleZh': 'Chinese Title',
    'campaignForm.titleEn': 'English Title',
    'campaignForm.titleTh': 'Thai Title',
    'campaignForm.descriptionZh': 'Chinese Description',
    'campaignForm.descriptionEn': 'English Description',
    'campaignForm.descriptionTh': 'Thai Description',
    'campaignForm.couponSettings': 'Coupon Settings',
    'campaignForm.discountType': 'Discount Type',
    'campaignForm.couponValue': 'Coupon Value',
    'campaignForm.startAt': 'Start Time',
    'campaignForm.endAt': 'End Time',
    'campaignForm.maxPerUser': 'Max Per User',
    'campaignForm.maxTotal': 'Total Stock (Empty = Unlimited)',
    'campaignForm.isActive': 'Enable Campaign',
    
    // Discount Types
    'discountType.final_price': 'Final Price',
    'discountType.gift_card': 'Gift Card',
    'discountType.cash_voucher': 'Cash Voucher',
    'discountType.full_reduction': 'Full Reduction',
    'discountType.percentage_off': 'Percentage Off',
    
    // Languages
    'language.zh-cn': '中文',
    'language.en-us': 'English',
    'language.th-th': 'ไทย',
  },
  'th-th': {
    // Common
    'common.logout': 'ออกจากระบบ',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.create': 'สร้าง',
    'common.search': 'ค้นหา',
    'common.loading': 'กำลังโหลด...',
    'common.saving': 'กำลังบันทึก...',
    'common.success': 'สำเร็จ',
    'common.error': 'ข้อผิดพลาด',
    'common.confirm': 'ยืนยัน',
    'common.welcome': 'ยินดีต้อนรับ',
    'common.chinese': 'ภาษาจีน',
    'common.english': 'ภาษาอังกฤษ',
    'common.thai': 'ภาษาไทย',
    
    // Navigation
    'nav.stores': 'จัดการร้านค้า',
    'nav.campaigns': 'จัดการแคมเปญ',
    'nav.dashboard': 'แดชบอร์ด',
    
    // Login
    'login.title': 'เข้าสู่ระบบผู้ดูแล',
    'login.email': 'อีเมล',
    'login.password': 'รหัสผ่าน',
    'login.submit': 'เข้าสู่ระบบ',
    'login.emailPlaceholder': 'กรุณากรอกอีเมล',
    'login.passwordPlaceholder': 'กรุณากรอกรหัสผ่าน',
    
    // Stores
    'stores.title': 'จัดการร้านค้า',
    'stores.addStore': 'เพิ่มร้านค้า',
    'stores.allStores': 'ร้านค้าทั้งหมด',
    'stores.image': 'รูปภาพ',
    'stores.noImage': 'ไม่มีรูปภาพ',
    'stores.name': 'ชื่อ',
    'stores.brand': 'แบรนด์',
    'stores.city': 'เมือง',
    'stores.address': 'ที่อยู่',
    'stores.phone': 'โทรศัพท์',
    'stores.latitude': 'ละติจูด',
    'stores.longitude': 'ลองจิจูด',
    'stores.imageUrl': 'URL รูปภาพ',
    'stores.rating': 'คะแนน',
    'stores.status': 'สถานะ',
    'stores.actions': 'การดำเนินการ',
    'stores.active': 'เปิดใช้งาน',
    'stores.inactive': 'ปิดใช้งาน',
    'stores.createTitle': 'สร้างร้านค้า',
    'stores.editTitle': 'แก้ไขร้านค้า',
    'stores.deleteConfirm': 'คุณแน่ใจหรือไม่ที่จะลบร้านค้านี้?',
    'stores.createSuccess': 'สร้างร้านค้าสำเร็จ',
    'stores.updateSuccess': 'อัปเดตร้านค้าสำเร็จ',
    'stores.deleteSuccess': 'ลบร้านค้าสำเร็จ',
    'stores.createError': 'ไม่สามารถสร้างร้านค้าได้',
    'stores.updateError': 'ไม่สามารถอัปเดตร้านค้าได้',
    'stores.deleteError': 'ไม่สามารถลบร้านค้าได้',
    'stores.noData': 'ไม่มีข้อมูลร้านค้า',
    'stores.searchAddress': 'ค้นหาที่อยู่ Google',
    'stores.searchPlaceholder': 'ค้นหาที่อยู่...',
    'stores.typeToSearch': 'พิมพ์เพื่อค้นหาที่อยู่',
    'stores.searchHelp': 'ใช้ Google Maps เพื่อกรอกข้อมูลร้านค้าอัตโนมัติ (ชื่อ, ที่อยู่, พิกัด, คะแนน ฯลฯ)',
    'stores.noResults': 'ไม่พบที่อยู่',
    'stores.placeSelected': 'กรอกข้อมูลที่อยู่อัตโนมัติแล้ว',
    'stores.placeDetailsError': 'ไม่สามารถรับรายละเอียดสถานที่ได้',
    
    // Campaigns
    'campaigns.title': 'จัดการแคมเปญ',
    'campaigns.createNew': 'สร้างแคมเปญ',
    'campaigns.addCampaign': 'เพิ่มแคมเปญ',
    'campaigns.allCampaigns': 'แคมเปญทั้งหมด',
    'campaigns.campaignTitle': 'ชื่อเรื่อง',
    'campaigns.couponType': 'ประเภท',
    'campaigns.couponValue': 'มูลค่า',
    'campaigns.startTime': 'เวลาเริ่มต้น',
    'campaigns.endTime': 'เวลาสิ้นสุด',
    'campaigns.startDate': 'วันเริ่มต้น',
    'campaigns.endDate': 'วันสิ้นสุด',
    'campaigns.status': 'สถานะ',
    'campaigns.actions': 'การดำเนินการ',
    'campaigns.active': 'เปิดใช้งาน',
    'campaigns.inactive': 'ปิดใช้งาน',
    'campaigns.createTitle': 'สร้างแคมเปญ',
    'campaigns.editTitle': 'แก้ไขแคมเปญ',
    'campaigns.editCampaign': 'แก้ไขแคมเปญ',
    'campaigns.deleteConfirm': 'คุณแน่ใจหรือไม่ที่จะลบแคมเปญนี้?',
    'campaigns.createSuccess': 'สร้างแคมเปญสำเร็จ',
    'campaigns.updateSuccess': 'อัปเดตแคมเปญสำเร็จ',
    'campaigns.deleteSuccess': 'ลบแคมเปญสำเร็จ',
    'campaigns.createError': 'ไม่สามารถสร้างแคมเปญได้',
    'campaigns.updateError': 'ไม่สามารถอัปเดตแคมเปญได้',
    'campaigns.deleteError': 'ไม่สามารถลบแคมเปญได้',
    'campaigns.noData': 'ไม่มีข้อมูลแคมเปญ',
    'campaigns.noCampaigns': 'ไม่มีแคมเปญ',
    'campaigns.manageStores': 'จัดการความสัมพันธ์ร้านค้า',
    'campaigns.autoTranslate': 'แปลอัตโนมัติ (AI)',
    'campaigns.translating': 'กำลังแปล...',
    'campaigns.translateSuccess': 'แปลเสร็จสิ้น',
    'campaigns.translateError': 'การแปลล้มเหลว',
    'campaigns.storesUpdateSuccess': 'อัปเดตความสัมพันธ์ร้านค้าสำเร็จ',
    'campaigns.storesUpdateError': 'ไม่สามารถอัปเดตความสัมพันธ์ร้านค้าได้',
    'campaigns.basicInfo': 'ข้อมูลพื้นฐาน',
    'campaigns.description': 'คำอธิบาย',
    'campaigns.titleLang': 'ภาษาหลักของชื่อเรื่อง',
    'campaigns.multiLanguageContent': 'เนื้อหาหลายภาษา (ตัวเลือก)',
    'campaigns.titleChinese': 'ชื่อเรื่องภาษาจีน',
    'campaigns.titleEnglish': 'ชื่อเรื่องภาษาอังกฤษ',
    'campaigns.titleThai': 'ชื่อเรื่องภาษาไทย',
    'campaigns.descriptionChinese': 'คำอธิบายภาษาจีน',
    'campaigns.descriptionEnglish': 'คำอธิบายภาษาอังกฤษ',
    'campaigns.descriptionThai': 'คำอธิบายภาษาไทย',
    'campaigns.couponSettings': 'การตั้งค่าคูปอง',
    'campaigns.maxPerUser': 'สูงสุดต่อผู้ใช้',
    'campaigns.maxTotal': 'สต็อกทั้งหมด (ว่าง = ไม่จำกัด)',
    'campaigns.enableCampaign': 'เปิดใช้งานแคมเปญ',
    'campaigns.finalPrice': 'ราคาสุดท้าย',
    'campaigns.giftCard': 'บัตรของขวัญ',
    'campaigns.cashVoucher': 'บัตรกำนัลเงินสด',
    'campaigns.fullReduction': 'ลดเต็มจำนวน',
    'campaigns.percentageOff': 'เปอร์เซ็นต์ส่วนลด',
    
    // Campaign Form
    'campaignForm.basicInfo': 'ข้อมูลพื้นฐาน',
    'campaignForm.titleLang': 'ภาษาหลักของชื่อเรื่อง',
    'campaignForm.title': 'ชื่อเรื่อง',
    'campaignForm.description': 'คำอธิบาย',
    'campaignForm.multiLang': 'เนื้อหาหลายภาษา (ตัวเลือก)',
    'campaignForm.titleZh': 'ชื่อเรื่องภาษาจีน',
    'campaignForm.titleEn': 'ชื่อเรื่องภาษาอังกฤษ',
    'campaignForm.titleTh': 'ชื่อเรื่องภาษาไทย',
    'campaignForm.descriptionZh': 'คำอธิบายภาษาจีน',
    'campaignForm.descriptionEn': 'คำอธิบายภาษาอังกฤษ',
    'campaignForm.descriptionTh': 'คำอธิบายภาษาไทย',
    'campaignForm.couponSettings': 'การตั้งค่าคูปอง',
    'campaignForm.discountType': 'ประเภทส่วนลด',
    'campaignForm.couponValue': 'มูลค่าคูปอง',
    'campaignForm.startAt': 'เวลาเริ่มต้น',
    'campaignForm.endAt': 'เวลาสิ้นสุด',
    'campaignForm.maxPerUser': 'สูงสุดต่อผู้ใช้',
    'campaignForm.maxTotal': 'สต็อกทั้งหมด (ว่าง = ไม่จำกัด)',
    'campaignForm.isActive': 'เปิดใช้งานแคมเปญ',
    
    // Discount Types
    'discountType.final_price': 'ราคาสุดท้าย',
    'discountType.gift_card': 'บัตรของขวัญ',
    'discountType.cash_voucher': 'บัตรกำนัลเงินสด',
    'discountType.full_reduction': 'ลดเต็มจำนวน',
    'discountType.percentage_off': 'เปอร์เซ็นต์ส่วนลด',
    
    // Languages
    'language.zh-cn': '中文',
    'language.en-us': 'English',
    'language.th-th': 'ไทย',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'zh-cn';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
