import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { queryClient } from '@/lib/queryClient';

type Language = 'zh-cn' | 'en-us' | 'th-th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  'zh-cn': {
    // Common
    'common.logout': '登出',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.search': '搜索',
    'common.loading': '加载中...',
    'common.saving': '保存中...',
    'common.success': '成功',
    'common.error': '错误',
    'common.confirm': '确认',
    'common.welcome': '欢迎',
    'common.chinese': '中文',
    'common.english': '英文',
    'common.thai': '泰文',
    'common.page': '第',
    'common.previous': '上一页',
    'common.next': '下一页',
    
    // Navigation
    'nav.stores': '门店管理',
    'nav.campaigns': '活动管理',
    'nav.dashboard': '数据面板',
    
    // Login
    'login.title': '管理后台登录',
    'login.email': '邮箱',
    'login.password': '密码',
    'login.submit': '登录',
    'login.emailPlaceholder': '请输入邮箱',
    'login.passwordPlaceholder': '请输入密码',
    
    // Stores
    'stores.title': '门店管理',
    'stores.addStore': '新建门店',
    'stores.allStores': '所有门店',
    'stores.image': '图片',
    'stores.noImage': '无图片',
    'stores.name': '名称',
    'stores.brand': '品牌',
    'stores.city': '城市',
    'stores.address': '地址',
    'stores.phone': '电话',
    'stores.latitude': '纬度',
    'stores.longitude': '经度',
    'stores.imageUrl': '图片网址',
    'stores.rating': '评分',
    'stores.status': '状态',
    'stores.actions': '操作',
    'stores.cityHelp': '填写府/城市名称（如Bangkok、นนทบุรี）。建议使用谷歌地图自动填充。',
    'stores.active': '启用',
    'stores.inactive': '禁用',
    'stores.createTitle': '新建门店',
    'stores.editTitle': '编辑门店',
    'stores.deleteConfirm': '确定要删除此门店吗？',
    'stores.createSuccess': '门店创建成功',
    'stores.updateSuccess': '门店更新成功',
    'stores.deleteSuccess': '门店删除成功',
    'stores.createError': '创建门店失败',
    'stores.updateError': '更新门店失败',
    'stores.deleteError': '删除门店失败',
    'stores.noData': '暂无门店数据',
    'stores.searchAddress': 'Google地址搜索',
    'stores.searchPlaceholder': '搜索地址...',
    'stores.typeToSearch': '输入地址开始搜索',
    'stores.searchHelp': '使用Google地图搜索自动填充门店信息（名称、地址、经纬度、评分等）',
    'stores.noResults': '未找到相关地址',
    'stores.placeSelected': '地址信息已自动填充',
    'stores.placeDetailsError': '获取地址详情失败',
    'stores.storeImage': '门店图片',
    'stores.uploadImage': '上传图片',
    'stores.uploading': '上传中...',
    'stores.removeImage': '移除图片',
    'stores.imageUrlPlaceholder': '或输入图片网址 https://...',
    'stores.imageHelp': '支持上传图片文件（最大5MB）或输入图片网址',
    'stores.imageUploaded': '图片上传成功',
    'stores.uploadError': '图片上传失败',
    'stores.invalidImageType': '只支持图片文件',
    'stores.imageTooLarge': '图片大小不能超过5MB',
    'stores.floorInfo': '楼层/位置信息',
    'stores.floorInfoPlaceholder': '例如：3楼，星巴克旁边',
    'stores.floorInfoHelp': '店中店位置描述，帮助用户找到店铺（可选）',
    
    // Staff Authorization
    'staff.title': '核销授权',
    'staff.manage': '管理核销授权',
    'staff.addNew': '添加新授权',
    'staff.staffName': '员工姓名',
    'staff.staffId': '员工编号',
    'staff.phone': '电话号码',
    'staff.status': '状态',
    'staff.boundUser': '绑定用户',
    'staff.pending': '待绑定',
    'staff.bound': '已绑定',
    'staff.createSuccess': '员工授权创建成功',
    'staff.deleteSuccess': '员工授权删除成功',
    'staff.unbindSuccess': '员工解绑成功',
    'staff.createError': '创建员工授权失败',
    'staff.deleteError': '删除员工授权失败',
    'staff.unbindError': '解绑员工失败',
    'staff.qrCode': '授权二维码',
    'staff.qrCodeDesc': '员工需使用LINE账号扫描此二维码完成授权',
    'staff.phoneVerification': '需要手机号验证',
    'staff.noAuthorizations': '暂无员工授权。点击上方创建新授权。',
    'staff.namePlaceholder': '请输入员工姓名',
    'staff.idPlaceholder': '请输入员工编号',
    'staff.phonePlaceholder': '请输入电话号码',
    'staff.createButton': '创建授权',
    'staff.qrCodeLink': '此授权链接将绑定到员工的LINE账号',
    'staff.unknown': '未知',
    'staff.activeList': '激活的员工授权',
    'staff.copyLink': '复制链接',
    'staff.linkCopied': '链接已复制',
    'staff.authLink': '授权链接',
    
    // Staff Binding
    'staffBind.title': '员工授权',
    'staffBind.description': '完成授权以核销优惠券',
    'staffBind.store': '店铺',
    'staffBind.staffInfo': '员工信息',
    'staffBind.name': '姓名',
    'staffBind.id': 'ID',
    'staffBind.phone': '电话',
    'staffBind.phoneVerificationRequired': '需要手机号验证',
    'staffBind.phoneVerificationDesc': '您的LINE账号电话号码必须与注册的员工电话号码匹配才能完成授权。',
    'staffBind.authorizeButton': '使用LINE授权',
    'staffBind.authorizing': '授权中...',
    'staffBind.success': '授权成功！',
    'staffBind.successDesc': '您现在可以在此店铺核销优惠券',
    'staffBind.failed': '授权失败',
    'staffBind.redirecting': '正在跳转到首页...',
    'staffBind.backHome': '返回首页',
    'staffBind.missingToken': '缺少授权令牌',
    'staffBind.invalidToken': '无效的授权令牌',
    'staffBind.alreadyUsed': '此授权已被使用',
    'staffBind.mustUseLine': '必须从LINE应用打开此页面',
    
    // Campaigns
    'campaigns.title': '活动管理',
    'campaigns.createNew': '新建活动',
    'campaigns.addCampaign': '新建活动',
    'campaigns.allCampaigns': '所有活动',
    'campaigns.campaignTitle': '标题',
    'campaigns.couponType': '券类型',
    'campaigns.couponValue': '券值',
    'campaigns.discount': '折扣',
    'campaigns.discountPlaceholder': '例如：80（表示8折）',
    'campaigns.discountHelp': '请输入1-100的数字，例如80表示8折',
    'campaigns.minAmount': '满额',
    'campaigns.minAmountPlaceholder': '例如：500',
    'campaigns.reductionAmount': '减额',
    'campaigns.reductionAmountPlaceholder': '例如：100',
    'campaigns.originalPrice': '原价',
    'campaigns.originalPricePlaceholder': '例如：1000',
    'campaigns.finalPriceValue': '最终价格',
    'campaigns.finalPricePlaceholder': '例如：800',
    'campaigns.faceValue': '面值',
    'campaigns.faceValuePlaceholder': '例如：500',
    'campaigns.startTime': '开始时间',
    'campaigns.endTime': '结束时间',
    'campaigns.startDate': '开始日期',
    'campaigns.endDate': '结束日期',
    'campaigns.status': '状态',
    'campaigns.actions': '操作',
    'campaigns.active': '启用',
    'campaigns.inactive': '禁用',
    'campaigns.createTitle': '新建活动',
    'campaigns.editTitle': '编辑活动',
    'campaigns.editCampaign': '编辑活动',
    'campaigns.deleteConfirm': '确定要删除此活动吗？',
    'campaigns.createSuccess': '活动创建成功',
    'campaigns.updateSuccess': '活动更新成功',
    'campaigns.deleteSuccess': '活动删除成功',
    'campaigns.createError': '创建活动失败',
    'campaigns.updateError': '更新活动失败',
    'campaigns.deleteError': '删除活动失败',
    'campaigns.noData': '暂无活动数据',
    'campaigns.noCampaigns': '暂无活动',
    'campaigns.manageStores': '门店关联管理',
    'campaigns.autoTranslate': 'AI自动翻译',
    'campaigns.translating': 'AI翻译中...',
    'campaigns.translateSuccess': 'AI翻译完成',
    'campaigns.translateError': 'AI翻译失败',
    'campaigns.storesUpdateSuccess': '门店关联更新成功',
    'campaigns.storesUpdateError': '门店关联更新失败',
    'campaigns.basicInfo': '基本信息',
    'campaigns.description': '描述',
    'campaigns.titleLang': '标题主语言',
    'campaigns.multiLanguageContent': '多语言内容（可选）',
    'campaigns.titleChinese': '中文标题',
    'campaigns.titleEnglish': '英文标题',
    'campaigns.titleThai': '泰文标题',
    'campaigns.descriptionChinese': '中文描述',
    'campaigns.descriptionEnglish': '英文描述',
    'campaigns.descriptionThai': '泰文描述',
    'campaigns.couponSettings': '券设置',
    'campaigns.maxPerUser': '每人限领',
    'campaigns.maxTotal': '总库存（留空=无限）',
    'campaigns.enableCampaign': '启用活动',
    'campaigns.finalPrice': '特价',
    'campaigns.giftCard': '礼品卡',
    'campaigns.cashVoucher': '现金券',
    'campaigns.fullReduction': '满减',
    'campaigns.percentageOff': '折扣',
    'campaigns.mediaFiles': '媒体文件 (1-5张图片或1个视频)',
    'campaigns.participatingStores': '参与门店',
    'campaigns.selectCity': '选择城市',
    'campaigns.selectAllCities': '全选城市',
    'campaigns.deselectAllCities': '取消全选城市',
    'campaigns.storesSelected': '已选 {count} 个门店',
    'campaigns.filteredStoresAvailable': '（筛选后可选 {count} 个）',
    'campaigns.selectAllStores': '全选门店',
    'campaigns.deselectAllStores': '取消全选门店',
    'campaigns.selectCityFirst': '请先选择城市',
    
    // Campaign Form
    'campaignForm.basicInfo': '基本信息',
    'campaignForm.titleLang': '标题主语言',
    'campaignForm.title': '标题',
    'campaignForm.description': '描述',
    'campaignForm.multiLang': '多语言内容（可选）',
    'campaignForm.titleZh': '中文标题',
    'campaignForm.titleEn': '英文标题',
    'campaignForm.titleTh': '泰文标题',
    'campaignForm.descriptionZh': '中文描述',
    'campaignForm.descriptionEn': '英文描述',
    'campaignForm.descriptionTh': '泰文描述',
    'campaignForm.couponSettings': '券设置',
    'campaignForm.discountType': '券类型',
    'campaignForm.couponValue': '券值',
    'campaignForm.startAt': '开始时间',
    'campaignForm.endAt': '结束时间',
    'campaignForm.maxPerUser': '每人限领',
    'campaignForm.maxTotal': '总库存（留空=无限）',
    'campaignForm.isActive': '启用活动',
    
    // Discount Types
    'discountType.final_price': '特价',
    'discountType.gift_card': '礼品卡',
    'discountType.cash_voucher': '现金券',
    'discountType.full_reduction': '满减',
    'discountType.percentage_off': '折扣',
    
    // Languages
    'language.zh-cn': '中文',
    'language.en-us': 'English',
    'language.th-th': 'ไทย',
    
    // Media Uploader
    'mediaUploader.imageMode': '图片模式',
    'mediaUploader.videoMode': '视频模式',
    'mediaUploader.maxImages': '最多',
    'mediaUploader.maxVideos': '最多',
    'mediaUploader.images': '张图片',
    'mediaUploader.videos': '个视频',
    'mediaUploader.image': '图片',
    'mediaUploader.video': '视频',
    'mediaUploader.switchModeTitle': '切换媒体类型？',
    'mediaUploader.switchModeDescription': '切换到{newMode}模式将清空当前已上传的{currentMode}。此操作无法撤销。',
    'mediaUploader.confirmSwitch': '确认切换',
    'mediaUploader.fileTypeError': '只支持图片或视频文件',
    'mediaUploader.onlyImagesAllowed': '当前只能上传图片',
    'mediaUploader.onlyVideosAllowed': '当前只能上传视频',
    'mediaUploader.maxImagesExceeded': '最多只能上传 {max} 张图片',
    'mediaUploader.maxVideosExceeded': '最多只能上传 {max} 个视频',
    'mediaUploader.uploadSuccess': '上传成功',
    'mediaUploader.uploadError': '上传失败，请重试',
    'mediaUploader.uploading': '上传中... {progress}%',
    'mediaUploader.releaseToUpload': '释放以上传',
    'mediaUploader.clickOrDrag': '点击或拖拽文件到此处',
    'mediaUploader.supportedImages': '支持上传 {max} 张图片',
    'mediaUploader.supportedVideos': '支持上传 {max} 个视频',
    
    // Campaign Detail Page
    'campaign.notFound': '活动不存在',
    'campaign.notFoundDesc': '该活动可能已下线或不存在',
    'campaign.expired': '已过期',
    'campaign.active': '进行中',
    'campaign.originalPrice': '原价',
    'campaign.period': '活动日期',
    'campaign.stock': '剩余',
    'campaign.limitPerUser': '每人限领',
    'campaign.claimed': '已领',
    'campaign.claimNow': '立即领取',
    'campaign.claiming': '领取中...',
    'campaign.claimWithLine': '用 LINE 一键领取',
    'campaign.soldOut': '已抢光',
    'campaign.reachedLimit': '已达领取上限',
    'campaign.claimSuccess': '领券成功',
    'campaign.claimSuccessDesc': '您可以在"我的优惠券"中查看',
    'campaign.claimError': '领券失败',
    'campaign.liffNotReady': '请在LINE中打开',
    'campaign.applicableStores': '适用门店',
    'campaign.viewMyCoupons': '查看我的优惠券',
    'campaign.loginDialogTitle': '使用 LINE 登录',
    'campaign.loginDialogDesc': '优惠券会保存在你的 LINE 账号里，请先用 LINE 一键登录',
    'campaign.loginAndClaim': '使用 LINE 登录并领取',
    'campaign.loggingIn': '登录中...',
    'campaign.webLoginNotImplemented': '请在LINE应用中打开链接',
    'campaign.rules': '活动规则',
    'campaign.viewRules': '请查看活动规则',
    'campaign.nearestStores': '最近的门店',
    'campaign.callStore': '拨打电话',
    'campaign.navigate': '导航',
    'campaign.navigateAria': '导航至 {store}',
    
    // My Coupons Page
    'myCoupons.title': '我的优惠券',
    'myCoupons.loginRequired': '请先登录',
    'myCoupons.loginDesc': '使用LINE账号登录查看您的优惠券',
    'myCoupons.all': '全部',
    'myCoupons.noCoupons': '暂无优惠券',
    
    // Coupon
    'coupon.unused': '未使用',
    'coupon.used': '已使用',
    'coupon.expired': '已过期',
    'coupon.status': '状态',
    'coupon.value': '优惠值',
    'coupon.validUntil': '有效期至',
    'coupon.issuedAt': '领取时间',
    'coupon.usedAt': '使用时间',
    'coupon.scanToRedeem': '向店员出示此二维码以核销',
    
    // Login
    'login.success': '登录成功',
    'login.failed': '登录失败',
    
    // Staff OA - Redeem Page
    'staffRedeem.title': '店员核销',
    'staffRedeem.description': '请输入8位数字核销码或扫描用户二维码',
    'staffRedeem.codeLabel': '核销码（8位数字）',
    'staffRedeem.codePlaceholder': '00000000',
    'staffRedeem.query': '查询',
    'staffRedeem.querying': '查询中...',
    'staffRedeem.enterCode': '请输入核销码',
    'staffRedeem.enterCodeDesc': '请输入8位数字核销码',
    'staffRedeem.invalidFormat': '核销码格式错误',
    'staffRedeem.invalidFormatDesc': '核销码必须是8位数字',
    'staffRedeem.querySuccess': '优惠券查询成功',
    'staffRedeem.querySuccessDesc': '请核对优惠券信息后确认核销',
    'staffRedeem.queryFailed': '查询失败',
    'staffRedeem.couponDetails': '优惠券详情',
    'staffRedeem.campaignName': '活动名称',
    'staffRedeem.customerName': '客户姓名',
    'staffRedeem.customerPhone': '客户电话',
    'staffRedeem.couponValue': '优惠金额',
    'staffRedeem.validUntil': '有效期至',
    'staffRedeem.notes': '备注',
    'staffRedeem.notesPlaceholder': '输入备注信息（可选）',
    'staffRedeem.confirmRedeem': '确认核销',
    'staffRedeem.redeeming': '核销中...',
    'staffRedeem.redeemSuccess': '核销成功',
    'staffRedeem.redeemSuccessDesc': '优惠券已成功核销',
    'staffRedeem.redeemFailed': '核销失败',
    'staffRedeem.redeemAnother': '核销下一张',
    'staffRedeem.loginRequired': '需要登录',
    'staffRedeem.loginRequiredDesc': '请先登录您的店员账号',
    'staffRedeem.backHome': '返回首页',
    'staffRedeem.recentRedemptions': '最近核销记录',
    'staffRedeem.noPermission': '该优惠券不属于您的门店，无法核销',
    
    // Staff OA - Stats Page
    'staffStats.title': '个人核销统计',
    'staffStats.summary': '汇总统计',
    'staffStats.today': '今日核销',
    'staffStats.thisWeek': '本周核销',
    'staffStats.thisMonth': '本月核销',
    'staffStats.byCampaign': '按活动统计',
    'staffStats.campaignName': '活动名称',
    'staffStats.count': '核销数量',
    'staffStats.recentRedemptions': '最近核销记录',
    'staffStats.time': '核销时间',
    'staffStats.code': '券码',
    'staffStats.noData': '暂无数据',
    
    // Staff OA - Campaign Page
    'staffCampaign.title': '当前活动',
    'staffCampaign.description': '查看正在进行的活动信息',
    'staffCampaign.activeCampaigns': '进行中的活动',
    'staffCampaign.campaignDetails': '活动详情',
    'staffCampaign.period': '活动期间',
    'staffCampaign.instructions': '执行说明',
    'staffCampaign.training': '培训内容',
    'staffCampaign.noCampaigns': '暂无进行中的活动',
    
    // Dashboard - Summary
    'dashboard.title': '数据面板',
    'dashboard.monthSelector': '月份选择',
    'dashboard.summary': '本月概览',
    'dashboard.issuedCount': '发券量',
    'dashboard.redeemedCount': '核销量',
    'dashboard.redemptionRate': '核销率',
    'dashboard.totalStores': '活跃门店',
    'dashboard.totalCampaigns': '活动总数',
    'dashboard.totalBrands': '合作品牌数',
    'dashboard.totalClaimed': '总领券数',
    'dashboard.totalRedeemed': '总核销数',
    'dashboard.conversionRate': '整体转化率',
    'dashboard.campaignDimension': '活动维度',
    'dashboard.brandDimension': '品牌维度',
    'dashboard.storeDimension': '门店维度',
    'dashboard.campaignStats': '活动统计',
    'dashboard.brandStats': '品牌统计',
    'dashboard.storeStats': '门店统计',
    'dashboard.campaignTitle': '活动标题',
    'dashboard.brandName': '品牌名称',
    'dashboard.storeName': '门店名称',
    'dashboard.storeCount': '门店数',
    'dashboard.city': '城市',
    'dashboard.noData': '暂无数据',
    
    // Dashboard - Campaigns
    'dashboard.campaigns.title': '活动维度统计',
    'dashboard.campaigns.id': '活动ID',
    'dashboard.campaigns.name': '活动名称',
    'dashboard.campaigns.brand': '品牌',
    'dashboard.campaigns.period': '活动期间',
    'dashboard.campaigns.storeCount': '参与门店',
    'dashboard.campaigns.claimedCount': '领券数',
    'dashboard.campaigns.redeemedCount': '核销数',
    'dashboard.campaigns.conversionRate': '转化率',
    'dashboard.campaigns.noData': '本月暂无活动数据',
    
    // Dashboard - Brands
    'dashboard.brands.title': '品牌维度统计',
    'dashboard.brands.name': '品牌名称',
    'dashboard.brands.campaignCount': '活动数',
    'dashboard.brands.storeCount': '门店数',
    'dashboard.brands.claimedCount': '领券数',
    'dashboard.brands.redeemedCount': '核销数',
    'dashboard.brands.conversionRate': '平均转化率',
    'dashboard.brands.noData': '本月暂无品牌数据',
    
    // Dashboard - Stores
    'dashboard.stores.title': '门店维度统计',
    'dashboard.stores.name': '门店名称',
    'dashboard.stores.brand': '品牌',
    'dashboard.stores.city': '城市',
    'dashboard.stores.campaignCount': '活动数',
    'dashboard.stores.claimedCount': '领券数',
    'dashboard.stores.redeemedCount': '核销数',
    'dashboard.stores.conversionRate': '转化率',
    'dashboard.stores.search': '搜索门店',
    'dashboard.stores.brandFilter': '品牌筛选',
    'dashboard.stores.noData': '本月暂无门店数据',
  },
  'en-us': {
    // Common
    'common.logout': 'Logout',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.saving': 'Saving...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.confirm': 'Confirm',
    'common.welcome': 'Welcome',
    'common.chinese': 'Chinese',
    'common.english': 'English',
    'common.thai': 'Thai',
    'common.page': 'Page',
    'common.previous': 'Previous',
    'common.next': 'Next',
    
    // Navigation
    'nav.stores': 'Stores',
    'nav.campaigns': 'Campaigns',
    'nav.dashboard': 'Dashboard',
    
    // Login
    'login.title': 'Admin Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.emailPlaceholder': 'Enter email',
    'login.passwordPlaceholder': 'Enter password',
    
    // Stores
    'stores.title': 'Stores Management',
    'stores.addStore': 'Add Store',
    'stores.allStores': 'All Stores',
    'stores.image': 'Image',
    'stores.noImage': 'No Image',
    'stores.name': 'Name',
    'stores.brand': 'Brand',
    'stores.city': 'City',
    'stores.address': 'Address',
    'stores.phone': 'Phone',
    'stores.latitude': 'Latitude',
    'stores.longitude': 'Longitude',
    'stores.imageUrl': 'Image URL',
    'stores.rating': 'Rating',
    'stores.status': 'Status',
    'stores.actions': 'Actions',
    'stores.cityHelp': 'Enter province/city name (e.g. Bangkok, นนทบุรี). Google Maps auto-fill recommended.',
    'stores.active': 'Active',
    'stores.inactive': 'Inactive',
    'stores.createTitle': 'Create Store',
    'stores.editTitle': 'Edit Store',
    'stores.deleteConfirm': 'Are you sure you want to delete this store?',
    'stores.createSuccess': 'Store created successfully',
    'stores.updateSuccess': 'Store updated successfully',
    'stores.deleteSuccess': 'Store deleted successfully',
    'stores.createError': 'Failed to create store',
    'stores.updateError': 'Failed to update store',
    'stores.deleteError': 'Failed to delete store',
    'stores.noData': 'No stores available',
    'stores.searchAddress': 'Google Address Search',
    'stores.searchPlaceholder': 'Search address...',
    'stores.typeToSearch': 'Type to search address',
    'stores.searchHelp': 'Use Google Maps to auto-fill store info (name, address, coordinates, rating, etc.)',
    'stores.noResults': 'No addresses found',
    'stores.placeSelected': 'Address info auto-filled',
    'stores.placeDetailsError': 'Failed to get place details',
    'stores.storeImage': 'Store Image',
    'stores.uploadImage': 'Upload Image',
    'stores.uploading': 'Uploading...',
    'stores.removeImage': 'Remove Image',
    'stores.imageUrlPlaceholder': 'Or enter image URL https://...',
    'stores.imageHelp': 'Upload an image file (max 5MB) or enter an image URL',
    'stores.imageUploaded': 'Image uploaded successfully',
    'stores.uploadError': 'Failed to upload image',
    'stores.invalidImageType': 'Only image files are supported',
    'stores.imageTooLarge': 'Image size cannot exceed 5MB',
    'stores.floorInfo': 'Floor/Location Info',
    'stores.floorInfoPlaceholder': 'e.g., 3rd Floor, near Starbucks',
    'stores.floorInfoHelp': 'Location description for shop-in-shop to help customers find the store (optional)',
    
    // Staff Authorization
    'staff.title': 'Redemption Authorization',
    'staff.manage': 'Manage Redemption Authorization',
    'staff.addNew': 'Add New Authorization',
    'staff.staffName': 'Staff Name',
    'staff.staffId': 'Staff ID',
    'staff.phone': 'Phone Number',
    'staff.status': 'Status',
    'staff.boundUser': 'Bound User',
    'staff.pending': 'Pending',
    'staff.bound': 'Bound',
    'staff.createSuccess': 'Staff authorization created successfully',
    'staff.deleteSuccess': 'Staff authorization deleted successfully',
    'staff.unbindSuccess': 'Staff unbounded successfully',
    'staff.createError': 'Failed to create staff authorization',
    'staff.deleteError': 'Failed to delete staff authorization',
    'staff.unbindError': 'Failed to unbind staff',
    'staff.qrCode': 'Authorization QR Code',
    'staff.qrCodeDesc': 'Staff member should scan this QR code with their LINE account to complete authorization',
    'staff.phoneVerification': 'Phone verification required',
    'staff.noAuthorizations': 'No staff authorizations yet. Create one above to get started.',
    'staff.namePlaceholder': 'Enter staff name',
    'staff.idPlaceholder': 'Enter staff ID',
    'staff.phonePlaceholder': 'Enter phone number',
    'staff.createButton': 'Create Authorization',
    'staff.qrCodeLink': 'This authorization link will bind to the staff member\'s LINE account',
    'staff.unknown': 'Unknown',
    'staff.activeList': 'Active Staff Authorizations',
    'staff.copyLink': 'Copy Link',
    'staff.linkCopied': 'Link Copied',
    'staff.authLink': 'Authorization Link',
    
    // Staff Binding
    'staffBind.title': 'Staff Authorization',
    'staffBind.description': 'Complete your authorization to redeem coupons',
    'staffBind.store': 'Store',
    'staffBind.staffInfo': 'Staff Information',
    'staffBind.name': 'Name',
    'staffBind.id': 'ID',
    'staffBind.phone': 'Phone',
    'staffBind.phoneVerificationRequired': 'Phone Verification Required',
    'staffBind.phoneVerificationDesc': 'Your LINE account\'s phone number must match the registered staff phone number to complete authorization.',
    'staffBind.authorizeButton': 'Authorize with LINE',
    'staffBind.authorizing': 'Authorizing...',
    'staffBind.success': 'Authorization Successful!',
    'staffBind.successDesc': 'You can now redeem coupons at this store',
    'staffBind.failed': 'Authorization Failed',
    'staffBind.redirecting': 'Redirecting to home...',
    'staffBind.backHome': 'Back to Home',
    'staffBind.missingToken': 'Missing authorization token',
    'staffBind.invalidToken': 'Invalid authorization token',
    'staffBind.alreadyUsed': 'This authorization has already been used',
    'staffBind.mustUseLine': 'This page must be opened from LINE app',
    
    // Campaigns
    'campaigns.title': 'Campaigns Management',
    'campaigns.createNew': 'Create Campaign',
    'campaigns.addCampaign': 'Add Campaign',
    'campaigns.allCampaigns': 'All Campaigns',
    'campaigns.campaignTitle': 'Title',
    'campaigns.couponType': 'Type',
    'campaigns.couponValue': 'Value',
    'campaigns.discount': 'Discount',
    'campaigns.discountPlaceholder': 'e.g.: 80 (means 20% off)',
    'campaigns.discountHelp': 'Enter a number from 1-100, e.g. 80 means 20% off',
    'campaigns.minAmount': 'Minimum Amount',
    'campaigns.minAmountPlaceholder': 'e.g.: 500',
    'campaigns.reductionAmount': 'Reduction Amount',
    'campaigns.reductionAmountPlaceholder': 'e.g.: 100',
    'campaigns.originalPrice': 'Original Price',
    'campaigns.originalPricePlaceholder': 'e.g.: 1000',
    'campaigns.finalPriceValue': 'Final Price',
    'campaigns.finalPricePlaceholder': 'e.g.: 800',
    'campaigns.faceValue': 'Face Value',
    'campaigns.faceValuePlaceholder': 'e.g.: 500',
    'campaigns.startTime': 'Start Time',
    'campaigns.endTime': 'End Time',
    'campaigns.startDate': 'Start Date',
    'campaigns.endDate': 'End Date',
    'campaigns.status': 'Status',
    'campaigns.actions': 'Actions',
    'campaigns.active': 'Active',
    'campaigns.inactive': 'Inactive',
    'campaigns.createTitle': 'Create Campaign',
    'campaigns.editTitle': 'Edit Campaign',
    'campaigns.editCampaign': 'Edit Campaign',
    'campaigns.deleteConfirm': 'Are you sure you want to delete this campaign?',
    'campaigns.createSuccess': 'Campaign created successfully',
    'campaigns.updateSuccess': 'Campaign updated successfully',
    'campaigns.deleteSuccess': 'Campaign deleted successfully',
    'campaigns.createError': 'Failed to create campaign',
    'campaigns.updateError': 'Failed to update campaign',
    'campaigns.deleteError': 'Failed to delete campaign',
    'campaigns.noData': 'No campaigns available',
    'campaigns.noCampaigns': 'No campaigns',
    'campaigns.manageStores': 'Manage Store Association',
    'campaigns.autoTranslate': 'Auto Translate (AI)',
    'campaigns.translating': 'Translating...',
    'campaigns.translateSuccess': 'Translation completed',
    'campaigns.translateError': 'Translation failed',
    'campaigns.storesUpdateSuccess': 'Store association updated successfully',
    'campaigns.storesUpdateError': 'Failed to update store association',
    'campaigns.basicInfo': 'Basic Information',
    'campaigns.description': 'Description',
    'campaigns.titleLang': 'Title Language',
    'campaigns.multiLanguageContent': 'Multi-language Content (Optional)',
    'campaigns.titleChinese': 'Chinese Title',
    'campaigns.titleEnglish': 'English Title',
    'campaigns.titleThai': 'Thai Title',
    'campaigns.descriptionChinese': 'Chinese Description',
    'campaigns.descriptionEnglish': 'English Description',
    'campaigns.descriptionThai': 'Thai Description',
    'campaigns.couponSettings': 'Coupon Settings',
    'campaigns.maxPerUser': 'Max Per User',
    'campaigns.maxTotal': 'Total Stock (Empty = Unlimited)',
    'campaigns.enableCampaign': 'Enable Campaign',
    'campaigns.finalPrice': 'Final Price',
    'campaigns.giftCard': 'Gift Card',
    'campaigns.cashVoucher': 'Cash Voucher',
    'campaigns.fullReduction': 'Full Reduction',
    'campaigns.percentageOff': 'Percentage Off',
    'campaigns.mediaFiles': 'Media Files (1-5 images or 1 video)',
    'campaigns.participatingStores': 'Participating Stores',
    'campaigns.selectCity': 'Select City',
    'campaigns.selectAllCities': 'Select All Cities',
    'campaigns.deselectAllCities': 'Deselect All Cities',
    'campaigns.storesSelected': '{count} stores selected',
    'campaigns.filteredStoresAvailable': '({count} available after filtering)',
    'campaigns.selectAllStores': 'Select All Stores',
    'campaigns.deselectAllStores': 'Deselect All Stores',
    'campaigns.selectCityFirst': 'Please select a city first',
    
    // Campaign Form
    'campaignForm.basicInfo': 'Basic Information',
    'campaignForm.titleLang': 'Title Language',
    'campaignForm.title': 'Title',
    'campaignForm.description': 'Description',
    'campaignForm.multiLang': 'Multi-language Content (Optional)',
    'campaignForm.titleZh': 'Chinese Title',
    'campaignForm.titleEn': 'English Title',
    'campaignForm.titleTh': 'Thai Title',
    'campaignForm.descriptionZh': 'Chinese Description',
    'campaignForm.descriptionEn': 'English Description',
    'campaignForm.descriptionTh': 'Thai Description',
    'campaignForm.couponSettings': 'Coupon Settings',
    'campaignForm.discountType': 'Discount Type',
    'campaignForm.couponValue': 'Coupon Value',
    'campaignForm.startAt': 'Start Time',
    'campaignForm.endAt': 'End Time',
    'campaignForm.maxPerUser': 'Max Per User',
    'campaignForm.maxTotal': 'Total Stock (Empty = Unlimited)',
    'campaignForm.isActive': 'Enable Campaign',
    
    // Discount Types
    'discountType.final_price': 'Final Price',
    'discountType.gift_card': 'Gift Card',
    'discountType.cash_voucher': 'Cash Voucher',
    'discountType.full_reduction': 'Full Reduction',
    'discountType.percentage_off': 'Percentage Off',
    
    // Languages
    'language.zh-cn': '中文',
    'language.en-us': 'English',
    'language.th-th': 'ไทย',
    
    // Media Uploader
    'mediaUploader.imageMode': 'Image Mode',
    'mediaUploader.videoMode': 'Video Mode',
    'mediaUploader.maxImages': 'Max',
    'mediaUploader.maxVideos': 'Max',
    'mediaUploader.images': 'images',
    'mediaUploader.videos': 'videos',
    'mediaUploader.image': 'image',
    'mediaUploader.video': 'video',
    'mediaUploader.switchModeTitle': 'Switch Media Type?',
    'mediaUploader.switchModeDescription': 'Switching to {newMode} mode will clear all uploaded {currentMode}. This action cannot be undone.',
    'mediaUploader.confirmSwitch': 'Confirm Switch',
    'mediaUploader.fileTypeError': 'Only images or videos are supported',
    'mediaUploader.onlyImagesAllowed': 'Only images can be uploaded currently',
    'mediaUploader.onlyVideosAllowed': 'Only videos can be uploaded currently',
    'mediaUploader.maxImagesExceeded': 'Maximum {max} images allowed',
    'mediaUploader.maxVideosExceeded': 'Maximum {max} videos allowed',
    'mediaUploader.uploadSuccess': 'Upload successful',
    'mediaUploader.uploadError': 'Upload failed, please try again',
    'mediaUploader.uploading': 'Uploading... {progress}%',
    'mediaUploader.releaseToUpload': 'Release to upload',
    'mediaUploader.clickOrDrag': 'Click or drag files here',
    'mediaUploader.supportedImages': 'Supports up to {max} images',
    'mediaUploader.supportedVideos': 'Supports up to {max} videos',
    
    // Campaign Detail Page
    'campaign.notFound': 'Campaign Not Found',
    'campaign.notFoundDesc': 'This campaign may have been removed or does not exist',
    'campaign.expired': 'Expired',
    'campaign.active': 'Active',
    'campaign.originalPrice': 'Original Price',
    'campaign.period': 'Period',
    'campaign.stock': 'Remaining',
    'campaign.limitPerUser': 'Limit Per User',
    'campaign.claimed': 'Claimed',
    'campaign.claimNow': 'Claim Now',
    'campaign.claiming': 'Claiming...',
    'campaign.claimWithLine': 'Claim with LINE',
    'campaign.soldOut': 'Sold Out',
    'campaign.reachedLimit': 'Limit Reached',
    'campaign.claimSuccess': 'Coupon Claimed',
    'campaign.claimSuccessDesc': 'View it in My Coupons',
    'campaign.claimError': 'Failed to claim coupon',
    'campaign.liffNotReady': 'Please open in LINE app',
    'campaign.applicableStores': 'Applicable Stores',
    'campaign.viewMyCoupons': 'View My Coupons',
    'campaign.loginDialogTitle': 'Login with LINE',
    'campaign.loginDialogDesc': 'Your coupons will be saved to your LINE account. Please login with LINE first.',
    'campaign.loginAndClaim': 'Login with LINE and Claim',
    'campaign.loggingIn': 'Logging in...',
    'campaign.webLoginNotImplemented': 'Please open this link in the LINE app',
    'campaign.rules': 'Campaign Rules',
    'campaign.viewRules': 'Please View Campaign Rules',
    'campaign.nearestStores': 'Nearest Stores',
    'campaign.callStore': 'Call',
    'campaign.navigate': 'Navigate',
    'campaign.navigateAria': 'Navigate to {store}',
    
    // My Coupons Page
    'myCoupons.title': 'My Coupons',
    'myCoupons.loginRequired': 'Login Required',
    'myCoupons.loginDesc': 'Login with your LINE account to view your coupons',
    'myCoupons.all': 'All',
    'myCoupons.noCoupons': 'No coupons yet',
    
    // Coupon
    'coupon.unused': 'Unused',
    'coupon.used': 'Used',
    'coupon.expired': 'Expired',
    'coupon.status': 'Status',
    'coupon.value': 'Value',
    'coupon.validUntil': 'Valid Until',
    'coupon.issuedAt': 'Claimed At',
    'coupon.usedAt': 'Used At',
    'coupon.scanToRedeem': 'Show this QR code to staff to redeem',
    
    // Login
    'login.success': 'Login successful',
    'login.failed': 'Login failed',
    
    // Staff OA - Redeem Page
    'staffRedeem.title': 'Staff Redemption',
    'staffRedeem.description': 'Enter 8-digit redemption code or scan user QR code',
    'staffRedeem.codeLabel': 'Redemption Code (8 digits)',
    'staffRedeem.codePlaceholder': '00000000',
    'staffRedeem.query': 'Query',
    'staffRedeem.querying': 'Querying...',
    'staffRedeem.enterCode': 'Please enter redemption code',
    'staffRedeem.enterCodeDesc': 'Please enter 8-digit redemption code',
    'staffRedeem.invalidFormat': 'Invalid code format',
    'staffRedeem.invalidFormatDesc': 'Redemption code must be 8 digits',
    'staffRedeem.querySuccess': 'Coupon query successful',
    'staffRedeem.querySuccessDesc': 'Please verify coupon information before redeeming',
    'staffRedeem.queryFailed': 'Query failed',
    'staffRedeem.couponDetails': 'Coupon Details',
    'staffRedeem.campaignName': 'Campaign',
    'staffRedeem.customerName': 'Customer',
    'staffRedeem.customerPhone': 'Phone',
    'staffRedeem.couponValue': 'Value',
    'staffRedeem.validUntil': 'Valid Until',
    'staffRedeem.notes': 'Notes',
    'staffRedeem.notesPlaceholder': 'Enter notes (optional)',
    'staffRedeem.confirmRedeem': 'Confirm Redemption',
    'staffRedeem.redeeming': 'Redeeming...',
    'staffRedeem.redeemSuccess': 'Redemption Successful',
    'staffRedeem.redeemSuccessDesc': 'Coupon has been redeemed successfully',
    'staffRedeem.redeemFailed': 'Redemption Failed',
    'staffRedeem.redeemAnother': 'Redeem Next',
    'staffRedeem.loginRequired': 'Login Required',
    'staffRedeem.loginRequiredDesc': 'Please login to your staff account',
    'staffRedeem.backHome': 'Back to Home',
    'staffRedeem.recentRedemptions': 'Recent Redemptions',
    'staffRedeem.noPermission': 'This coupon does not belong to your store',
    
    // Staff OA - Stats Page
    'staffStats.title': 'Personal Redemption Stats',
    'staffStats.summary': 'Summary',
    'staffStats.today': 'Today',
    'staffStats.thisWeek': 'This Week',
    'staffStats.thisMonth': 'This Month',
    'staffStats.byCampaign': 'By Campaign',
    'staffStats.campaignName': 'Campaign',
    'staffStats.count': 'Count',
    'staffStats.recentRedemptions': 'Recent Redemptions',
    'staffStats.time': 'Time',
    'staffStats.code': 'Code',
    'staffStats.noData': 'No data',
    
    // Staff OA - Campaign Page
    'staffCampaign.title': 'Current Campaigns',
    'staffCampaign.description': 'View active campaign information',
    'staffCampaign.activeCampaigns': 'Active Campaigns',
    'staffCampaign.campaignDetails': 'Campaign Details',
    'staffCampaign.period': 'Period',
    'staffCampaign.instructions': 'Instructions',
    'staffCampaign.training': 'Training',
    'staffCampaign.noCampaigns': 'No active campaigns',
    
    // Dashboard - Summary
    'dashboard.title': 'Dashboard',
    'dashboard.monthSelector': 'Month',
    'dashboard.summary': 'Monthly Overview',
    'dashboard.issuedCount': 'Issued',
    'dashboard.redeemedCount': 'Redeemed',
    'dashboard.redemptionRate': 'Redemption Rate',
    'dashboard.totalStores': 'Active Stores',
    'dashboard.totalCampaigns': 'Total Campaigns',
    'dashboard.totalBrands': 'Total Brands',
    'dashboard.totalClaimed': 'Total Claimed',
    'dashboard.totalRedeemed': 'Total Redeemed',
    'dashboard.conversionRate': 'Conversion Rate',
    'dashboard.campaignDimension': 'Campaigns',
    'dashboard.brandDimension': 'Brands',
    'dashboard.storeDimension': 'Stores',
    'dashboard.campaignStats': 'Campaign Statistics',
    'dashboard.brandStats': 'Brand Statistics',
    'dashboard.storeStats': 'Store Statistics',
    'dashboard.campaignTitle': 'Campaign',
    'dashboard.brandName': 'Brand',
    'dashboard.storeName': 'Store',
    'dashboard.storeCount': 'Stores',
    'dashboard.city': 'City',
    'dashboard.noData': 'No data',
    
    // Dashboard - Campaigns
    'dashboard.campaigns.title': 'Campaign Statistics',
    'dashboard.campaigns.id': 'ID',
    'dashboard.campaigns.name': 'Campaign',
    'dashboard.campaigns.brand': 'Brand',
    'dashboard.campaigns.period': 'Period',
    'dashboard.campaigns.storeCount': 'Stores',
    'dashboard.campaigns.claimedCount': 'Claimed',
    'dashboard.campaigns.redeemedCount': 'Redeemed',
    'dashboard.campaigns.conversionRate': 'Conv. Rate',
    'dashboard.campaigns.noData': 'No campaign data this month',
    
    // Dashboard - Brands
    'dashboard.brands.title': 'Brand Statistics',
    'dashboard.brands.name': 'Brand',
    'dashboard.brands.campaignCount': 'Campaigns',
    'dashboard.brands.storeCount': 'Stores',
    'dashboard.brands.claimedCount': 'Claimed',
    'dashboard.brands.redeemedCount': 'Redeemed',
    'dashboard.brands.conversionRate': 'Avg. Conv. Rate',
    'dashboard.brands.noData': 'No brand data this month',
    
    // Dashboard - Stores
    'dashboard.stores.title': 'Store Statistics',
    'dashboard.stores.name': 'Store',
    'dashboard.stores.brand': 'Brand',
    'dashboard.stores.city': 'City',
    'dashboard.stores.campaignCount': 'Campaigns',
    'dashboard.stores.claimedCount': 'Claimed',
    'dashboard.stores.redeemedCount': 'Redeemed',
    'dashboard.stores.conversionRate': 'Conv. Rate',
    'dashboard.stores.search': 'Search stores',
    'dashboard.stores.brandFilter': 'Brand filter',
    'dashboard.stores.noData': 'No store data this month',
  },
  'th-th': {
    // Common
    'common.logout': 'ออกจากระบบ',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.create': 'สร้าง',
    'common.search': 'ค้นหา',
    'common.loading': 'กำลังโหลด...',
    'common.saving': 'กำลังบันทึก...',
    'common.success': 'สำเร็จ',
    'common.error': 'ข้อผิดพลาด',
    'common.confirm': 'ยืนยัน',
    'common.welcome': 'ยินดีต้อนรับ',
    'common.chinese': 'ภาษาจีน',
    'common.english': 'ภาษาอังกฤษ',
    'common.thai': 'ภาษาไทย',
    'common.page': 'หน้า',
    'common.previous': 'ก่อนหน้า',
    'common.next': 'ถัดไป',
    
    // Navigation
    'nav.stores': 'จัดการร้านค้า',
    'nav.campaigns': 'จัดการแคมเปญ',
    'nav.dashboard': 'แดชบอร์ด',
    
    // Login
    'login.title': 'เข้าสู่ระบบผู้ดูแล',
    'login.email': 'อีเมล',
    'login.password': 'รหัสผ่าน',
    'login.submit': 'เข้าสู่ระบบ',
    'login.emailPlaceholder': 'กรุณากรอกอีเมล',
    'login.passwordPlaceholder': 'กรุณากรอกรหัสผ่าน',
    
    // Stores
    'stores.title': 'จัดการร้านค้า',
    'stores.addStore': 'เพิ่มร้านค้า',
    'stores.allStores': 'ร้านค้าทั้งหมด',
    'stores.image': 'รูปภาพ',
    'stores.noImage': 'ไม่มีรูปภาพ',
    'stores.name': 'ชื่อ',
    'stores.brand': 'แบรนด์',
    'stores.city': 'เมือง',
    'stores.address': 'ที่อยู่',
    'stores.phone': 'โทรศัพท์',
    'stores.latitude': 'ละติจูด',
    'stores.longitude': 'ลองจิจูด',
    'stores.imageUrl': 'URL รูปภาพ',
    'stores.rating': 'คะแนน',
    'stores.status': 'สถานะ',
    'stores.actions': 'การดำเนินการ',
    'stores.cityHelp': 'กรอกชื่อจังหวัด/เมือง (เช่น Bangkok, นนทบุรี) แนะนำให้ใช้ Google Maps เติมอัตโนมัติ',
    'stores.active': 'เปิดใช้งาน',
    'stores.inactive': 'ปิดใช้งาน',
    'stores.createTitle': 'สร้างร้านค้า',
    'stores.editTitle': 'แก้ไขร้านค้า',
    'stores.deleteConfirm': 'คุณแน่ใจหรือไม่ที่จะลบร้านค้านี้?',
    'stores.createSuccess': 'สร้างร้านค้าสำเร็จ',
    'stores.updateSuccess': 'อัปเดตร้านค้าสำเร็จ',
    'stores.deleteSuccess': 'ลบร้านค้าสำเร็จ',
    'stores.createError': 'ไม่สามารถสร้างร้านค้าได้',
    'stores.updateError': 'ไม่สามารถอัปเดตร้านค้าได้',
    'stores.deleteError': 'ไม่สามารถลบร้านค้าได้',
    'stores.noData': 'ไม่มีข้อมูลร้านค้า',
    'stores.searchAddress': 'ค้นหาที่อยู่ Google',
    'stores.searchPlaceholder': 'ค้นหาที่อยู่...',
    'stores.typeToSearch': 'พิมพ์เพื่อค้นหาที่อยู่',
    'stores.searchHelp': 'ใช้ Google Maps เพื่อกรอกข้อมูลร้านค้าอัตโนมัติ (ชื่อ, ที่อยู่, พิกัด, คะแนน ฯลฯ)',
    'stores.noResults': 'ไม่พบที่อยู่',
    'stores.placeSelected': 'กรอกข้อมูลที่อยู่อัตโนมัติแล้ว',
    'stores.placeDetailsError': 'ไม่สามารถรับรายละเอียดสถานที่ได้',
    'stores.storeImage': 'รูปภาพร้านค้า',
    'stores.uploadImage': 'อัพโหลดรูปภาพ',
    'stores.uploading': 'กำลังอัพโหลด...',
    'stores.removeImage': 'ลบรูปภาพ',
    'stores.imageUrlPlaceholder': 'หรือใส่ URL รูปภาพ https://...',
    'stores.imageHelp': 'รองรับการอัพโหลดไฟล์รูปภาพ (สูงสุด 5MB) หรือใส่ URL รูปภาพ',
    'stores.imageUploaded': 'อัพโหลดรูปภาพสำเร็จ',
    'stores.uploadError': 'อัพโหลดรูปภาพล้มเหลว',
    'stores.invalidImageType': 'รองรับเฉพาะไฟล์รูปภาพเท่านั้น',
    'stores.imageTooLarge': 'ขนาดรูปภาพต้องไม่เกิน 5MB',
    'stores.floorInfo': 'ข้อมูลชั้น/ที่ตั้ง',
    'stores.floorInfoPlaceholder': 'เช่น: ชั้น 3 ใกล้สตาร์บัคส์',
    'stores.floorInfoHelp': 'คำอธิบายตำแหน่งร้านค้าเพื่อช่วยให้ลูกค้าหาร้านได้ง่าย (ไม่บังคับ)',
    
    // Staff Authorization
    'staff.title': 'การอนุมัติการแลกคูปอง',
    'staff.manage': 'จัดการการอนุมัติการแลกคูปอง',
    'staff.addNew': 'เพิ่มการอนุมัติใหม่',
    'staff.staffName': 'ชื่อพนักงาน',
    'staff.staffId': 'รหัสพนักงาน',
    'staff.phone': 'เบอร์โทรศัพท์',
    'staff.status': 'สถานะ',
    'staff.boundUser': 'ผู้ใช้ที่เชื่อมโยง',
    'staff.pending': 'รอดำเนินการ',
    'staff.bound': 'เชื่อมโยงแล้ว',
    'staff.createSuccess': 'สร้างการอนุมัติพนักงานสำเร็จ',
    'staff.deleteSuccess': 'ลบการอนุมัติพนักงานสำเร็จ',
    'staff.unbindSuccess': 'ยกเลิกการเชื่อมโยงพนักงานสำเร็จ',
    'staff.createError': 'ไม่สามารถสร้างการอนุมัติพนักงานได้',
    'staff.deleteError': 'ไม่สามารถลบการอนุมัติพนักงานได้',
    'staff.unbindError': 'ไม่สามารถยกเลิกการเชื่อมโยงพนักงานได้',
    'staff.qrCode': 'QR Code การอนุมัติ',
    'staff.qrCodeDesc': 'พนักงานต้องสแกน QR Code นี้ด้วยบัญชี LINE เพื่อทำการอนุมัติให้เสร็จสมบูรณ์',
    'staff.phoneVerification': 'ต้องมีการยืนยันหมายเลขโทรศัพท์',
    'staff.noAuthorizations': 'ยังไม่มีการอนุมัติพนักงาน สร้างใหม่ด้านบนเพื่อเริ่มต้น',
    'staff.namePlaceholder': 'กรอกชื่อพนักงาน',
    'staff.idPlaceholder': 'กรอกรหัสพนักงาน',
    'staff.phonePlaceholder': 'กรอกเบอร์โทรศัพท์',
    'staff.createButton': 'สร้างการอนุมัติ',
    'staff.qrCodeLink': 'ลิงก์การอนุมัตินี้จะเชื่อมโยงกับบัญชี LINE ของพนักงาน',
    'staff.unknown': 'ไม่ทราบ',
    'staff.activeList': 'การอนุมัติพนักงานที่ใช้งานอยู่',
    'staff.copyLink': 'คัดลอกลิงก์',
    'staff.linkCopied': 'คัดลอกลิงก์แล้ว',
    'staff.authLink': 'ลิงก์การอนุมัติ',
    
    // Staff Binding
    'staffBind.title': 'การอนุมัติพนักงาน',
    'staffBind.description': 'ทำการอนุมัติให้เสร็จสมบูรณ์เพื่อแลกคูปอง',
    'staffBind.store': 'ร้านค้า',
    'staffBind.staffInfo': 'ข้อมูลพนักงาน',
    'staffBind.name': 'ชื่อ',
    'staffBind.id': 'รหัส',
    'staffBind.phone': 'โทรศัพท์',
    'staffBind.phoneVerificationRequired': 'ต้องมีการยืนยันหมายเลขโทรศัพท์',
    'staffBind.phoneVerificationDesc': 'หมายเลขโทรศัพท์ในบัญชี LINE ของคุณต้องตรงกับหมายเลขโทรศัพท์พนักงานที่ลงทะเบียนไว้เพื่อทำการอนุมัติให้เสร็จสมบูรณ์',
    'staffBind.authorizeButton': 'อนุมัติด้วย LINE',
    'staffBind.authorizing': 'กำลังอนุมัติ...',
    'staffBind.success': 'อนุมัติสำเร็จ!',
    'staffBind.successDesc': 'ตอนนี้คุณสามารถแลกคูปองที่ร้านนี้ได้',
    'staffBind.failed': 'การอนุมัติล้มเหลว',
    'staffBind.redirecting': 'กำลังเปลี่ยนเส้นทางไปหน้าแรก...',
    'staffBind.backHome': 'กลับหน้าแรก',
    'staffBind.missingToken': 'ขาดโทเค็นการอนุมัติ',
    'staffBind.invalidToken': 'โทเค็นการอนุมัติไม่ถูกต้อง',
    'staffBind.alreadyUsed': 'การอนุมัตินี้ถูกใช้ไปแล้ว',
    'staffBind.mustUseLine': 'ต้องเปิดหน้านี้จากแอป LINE',
    
    // Campaigns
    'campaigns.title': 'จัดการแคมเปญ',
    'campaigns.createNew': 'สร้างแคมเปญ',
    'campaigns.addCampaign': 'เพิ่มแคมเปญ',
    'campaigns.allCampaigns': 'แคมเปญทั้งหมด',
    'campaigns.campaignTitle': 'ชื่อเรื่อง',
    'campaigns.couponType': 'ประเภท',
    'campaigns.couponValue': 'มูลค่า',
    'campaigns.discount': 'ส่วนลด',
    'campaigns.discountPlaceholder': 'เช่น: 80 (หมายถึง ลด 20%)',
    'campaigns.discountHelp': 'กรอกตัวเลข 1-100 เช่น 80 หมายถึง ลด 20%',
    'campaigns.minAmount': 'ยอดขั้นต่ำ',
    'campaigns.minAmountPlaceholder': 'เช่น: 500',
    'campaigns.reductionAmount': 'ยอดลด',
    'campaigns.reductionAmountPlaceholder': 'เช่น: 100',
    'campaigns.originalPrice': 'ราคาเต็ม',
    'campaigns.originalPricePlaceholder': 'เช่น: 1000',
    'campaigns.finalPriceValue': 'ราคาสุดท้าย',
    'campaigns.finalPricePlaceholder': 'เช่น: 800',
    'campaigns.faceValue': 'มูลค่าหน้าบัตร',
    'campaigns.faceValuePlaceholder': 'เช่น: 500',
    'campaigns.startTime': 'เวลาเริ่มต้น',
    'campaigns.endTime': 'เวลาสิ้นสุด',
    'campaigns.startDate': 'วันเริ่มต้น',
    'campaigns.endDate': 'วันสิ้นสุด',
    'campaigns.status': 'สถานะ',
    'campaigns.actions': 'การดำเนินการ',
    'campaigns.active': 'เปิดใช้งาน',
    'campaigns.inactive': 'ปิดใช้งาน',
    'campaigns.createTitle': 'สร้างแคมเปญ',
    'campaigns.editTitle': 'แก้ไขแคมเปญ',
    'campaigns.editCampaign': 'แก้ไขแคมเปญ',
    'campaigns.deleteConfirm': 'คุณแน่ใจหรือไม่ที่จะลบแคมเปญนี้?',
    'campaigns.createSuccess': 'สร้างแคมเปญสำเร็จ',
    'campaigns.updateSuccess': 'อัปเดตแคมเปญสำเร็จ',
    'campaigns.deleteSuccess': 'ลบแคมเปญสำเร็จ',
    'campaigns.createError': 'ไม่สามารถสร้างแคมเปญได้',
    'campaigns.updateError': 'ไม่สามารถอัปเดตแคมเปญได้',
    'campaigns.deleteError': 'ไม่สามารถลบแคมเปญได้',
    'campaigns.noData': 'ไม่มีข้อมูลแคมเปญ',
    'campaigns.noCampaigns': 'ไม่มีแคมเปญ',
    'campaigns.manageStores': 'จัดการความสัมพันธ์ร้านค้า',
    'campaigns.autoTranslate': 'แปลอัตโนมัติ (AI)',
    'campaigns.translating': 'กำลังแปล...',
    'campaigns.translateSuccess': 'แปลเสร็จสิ้น',
    'campaigns.translateError': 'การแปลล้มเหลว',
    'campaigns.storesUpdateSuccess': 'อัปเดตความสัมพันธ์ร้านค้าสำเร็จ',
    'campaigns.storesUpdateError': 'ไม่สามารถอัปเดตความสัมพันธ์ร้านค้าได้',
    'campaigns.basicInfo': 'ข้อมูลพื้นฐาน',
    'campaigns.description': 'คำอธิบาย',
    'campaigns.titleLang': 'ภาษาหลักของชื่อเรื่อง',
    'campaigns.multiLanguageContent': 'เนื้อหาหลายภาษา (ตัวเลือก)',
    'campaigns.titleChinese': 'ชื่อเรื่องภาษาจีน',
    'campaigns.titleEnglish': 'ชื่อเรื่องภาษาอังกฤษ',
    'campaigns.titleThai': 'ชื่อเรื่องภาษาไทย',
    'campaigns.descriptionChinese': 'คำอธิบายภาษาจีน',
    'campaigns.descriptionEnglish': 'คำอธิบายภาษาอังกฤษ',
    'campaigns.descriptionThai': 'คำอธิบายภาษาไทย',
    'campaigns.couponSettings': 'การตั้งค่าคูปอง',
    'campaigns.maxPerUser': 'สูงสุดต่อผู้ใช้',
    'campaigns.maxTotal': 'สต็อกทั้งหมด (ว่าง = ไม่จำกัด)',
    'campaigns.enableCampaign': 'เปิดใช้งานแคมเปญ',
    'campaigns.finalPrice': 'ราคาสุดท้าย',
    'campaigns.giftCard': 'บัตรของขวัญ',
    'campaigns.cashVoucher': 'บัตรกำนัลเงินสด',
    'campaigns.fullReduction': 'ลดเต็มจำนวน',
    'campaigns.percentageOff': 'เปอร์เซ็นต์ส่วนลด',
    'campaigns.mediaFiles': 'ไฟล์มีเดีย (1-5 รูปภาพหรือ 1 วิดีโอ)',
    'campaigns.participatingStores': 'ร้านค้าที่เข้าร่วม',
    'campaigns.selectCity': 'เลือกเมือง',
    'campaigns.selectAllCities': 'เลือกทุกเมือง',
    'campaigns.deselectAllCities': 'ยกเลิกการเลือกทุกเมือง',
    'campaigns.storesSelected': 'เลือกแล้ว {count} ร้านค้า',
    'campaigns.filteredStoresAvailable': '(กรองแล้วมี {count} ร้านค้าที่สามารถเลือกได้)',
    'campaigns.selectAllStores': 'เลือกทุกร้านค้า',
    'campaigns.deselectAllStores': 'ยกเลิกการเลือกทุกร้านค้า',
    'campaigns.selectCityFirst': 'กรุณาเลือกเมืองก่อน',
    
    // Campaign Form
    'campaignForm.basicInfo': 'ข้อมูลพื้นฐาน',
    'campaignForm.titleLang': 'ภาษาหลักของชื่อเรื่อง',
    'campaignForm.title': 'ชื่อเรื่อง',
    'campaignForm.description': 'คำอธิบาย',
    'campaignForm.multiLang': 'เนื้อหาหลายภาษา (ตัวเลือก)',
    'campaignForm.titleZh': 'ชื่อเรื่องภาษาจีน',
    'campaignForm.titleEn': 'ชื่อเรื่องภาษาอังกฤษ',
    'campaignForm.titleTh': 'ชื่อเรื่องภาษาไทย',
    'campaignForm.descriptionZh': 'คำอธิบายภาษาจีน',
    'campaignForm.descriptionEn': 'คำอธิบายภาษาอังกฤษ',
    'campaignForm.descriptionTh': 'คำอธิบายภาษาไทย',
    'campaignForm.couponSettings': 'การตั้งค่าคูปอง',
    'campaignForm.discountType': 'ประเภทส่วนลด',
    'campaignForm.couponValue': 'มูลค่าคูปอง',
    'campaignForm.startAt': 'เวลาเริ่มต้น',
    'campaignForm.endAt': 'เวลาสิ้นสุด',
    'campaignForm.maxPerUser': 'สูงสุดต่อผู้ใช้',
    'campaignForm.maxTotal': 'สต็อกทั้งหมด (ว่าง = ไม่จำกัด)',
    'campaignForm.isActive': 'เปิดใช้งานแคมเปญ',
    
    // Discount Types
    'discountType.final_price': 'ราคาสุดท้าย',
    'discountType.gift_card': 'บัตรของขวัญ',
    'discountType.cash_voucher': 'บัตรกำนัลเงินสด',
    'discountType.full_reduction': 'ลดเต็มจำนวน',
    'discountType.percentage_off': 'เปอร์เซ็นต์ส่วนลด',
    
    // Languages
    'language.zh-cn': '中文',
    'language.en-us': 'English',
    'language.th-th': 'ไทย',
    
    // Media Uploader
    'mediaUploader.imageMode': 'โหมดรูปภาพ',
    'mediaUploader.videoMode': 'โหมดวิดีโอ',
    'mediaUploader.maxImages': 'สูงสุด',
    'mediaUploader.maxVideos': 'สูงสุด',
    'mediaUploader.images': 'รูปภาพ',
    'mediaUploader.videos': 'วิดีโอ',
    'mediaUploader.image': 'รูปภาพ',
    'mediaUploader.video': 'วิดีโอ',
    'mediaUploader.switchModeTitle': 'สลับประเภทสื่อ?',
    'mediaUploader.switchModeDescription': 'การสลับไปยังโหมด{newMode}จะลบ{currentMode}ที่อัปโหลดทั้งหมด การดำเนินการนี้ไม่สามารถยกเลิกได้',
    'mediaUploader.confirmSwitch': 'ยืนยันการสลับ',
    'mediaUploader.fileTypeError': 'รองรับเฉพาะไฟล์รูปภาพหรือวิดีโอ',
    'mediaUploader.onlyImagesAllowed': 'ขณะนี้สามารถอัปโหลดได้เฉพาะรูปภาพ',
    'mediaUploader.onlyVideosAllowed': 'ขณะนี้สามารถอัปโหลดได้เฉพาะวิดีโอ',
    'mediaUploader.maxImagesExceeded': 'อนุญาตให้อัปโหลดได้สูงสุด {max} รูปภาพ',
    'mediaUploader.maxVideosExceeded': 'อนุญาตให้อัปโหลดได้สูงสุด {max} วิดีโอ',
    'mediaUploader.uploadSuccess': 'อัปโหลดสำเร็จ',
    'mediaUploader.uploadError': 'อัปโหลดล้มเหลว กรุณาลองอีกครั้ง',
    'mediaUploader.uploading': 'กำลังอัปโหลด... {progress}%',
    'mediaUploader.releaseToUpload': 'ปล่อยเพื่ออัปโหลด',
    'mediaUploader.clickOrDrag': 'คลิกหรือลากไฟล์มาที่นี่',
    'mediaUploader.supportedImages': 'รองรับการอัปโหลดได้สูงสุด {max} รูปภาพ',
    'mediaUploader.supportedVideos': 'รองรับการอัปโหลดได้สูงสุด {max} วิดีโอ',
    
    // Campaign Detail Page
    'campaign.notFound': 'ไม่พบแคมเปญ',
    'campaign.notFoundDesc': 'แคมเปญนี้อาจถูกลบหรือไม่มีอยู่',
    'campaign.expired': 'หมดอายุ',
    'campaign.active': 'กำลังดำเนินการ',
    'campaign.originalPrice': 'ราคาเดิม',
    'campaign.period': 'ระยะเวลา',
    'campaign.stock': 'คงเหลือ',
    'campaign.limitPerUser': 'จำกัดต่อผู้ใช้',
    'campaign.claimed': 'รับแล้ว',
    'campaign.claimNow': 'รับคูปองเลย',
    'campaign.claiming': 'กำลังรับ...',
    'campaign.claimWithLine': 'รับคูปองด้วย LINE',
    'campaign.soldOut': 'หมดแล้ว',
    'campaign.reachedLimit': 'ถึงขีดจำกัดแล้ว',
    'campaign.claimSuccess': 'รับคูปองสำเร็จ',
    'campaign.claimSuccessDesc': 'ดูได้ในคูปองของฉัน',
    'campaign.claimError': 'รับคูปองไม่สำเร็จ',
    'campaign.liffNotReady': 'กรุณาเปิดในแอป LINE',
    'campaign.applicableStores': 'ร้านค้าที่ใช้ได้',
    'campaign.viewMyCoupons': 'ดูคูปองของฉัน',
    'campaign.loginDialogTitle': 'เข้าสู่ระบบด้วย LINE',
    'campaign.loginDialogDesc': 'คูปองจะถูกบันทึกในบัญชี LINE ของคุณ กรุณาเข้าสู่ระบบด้วย LINE ก่อน',
    'campaign.loginAndClaim': 'เข้าสู่ระบบด้วย LINE เพื่อรับคูปอง',
    'campaign.loggingIn': 'กำลังเข้าสู่ระบบ...',
    'campaign.webLoginNotImplemented': 'กรุณาเปิดลิงก์นี้ในแอป LINE',
    'campaign.rules': 'กฎกติกาแคมเปญ',
    'campaign.viewRules': 'โปรดดูกฎกติกาแคมเปญ',
    'campaign.nearestStores': 'ร้านค้าใกล้ที่สุด',
    'campaign.callStore': 'โทร',
    'campaign.navigate': 'นำทาง',
    'campaign.navigateAria': 'นำทางไปยัง {store}',
    
    // My Coupons Page
    'myCoupons.title': 'คูปองของฉัน',
    'myCoupons.loginRequired': 'จำเป็นต้องเข้าสู่ระบบ',
    'myCoupons.loginDesc': 'เข้าสู่ระบบด้วยบัญชี LINE เพื่อดูคูปองของคุณ',
    'myCoupons.all': 'ทั้งหมด',
    'myCoupons.noCoupons': 'ยังไม่มีคูปอง',
    
    // Coupon
    'coupon.unused': 'ยังไม่ได้ใช้',
    'coupon.used': 'ใช้แล้ว',
    'coupon.expired': 'หมดอายุ',
    'coupon.status': 'สถานะ',
    'coupon.value': 'มูลค่า',
    'coupon.validUntil': 'ใช้ได้ถึง',
    'coupon.issuedAt': 'วันที่รับ',
    'coupon.usedAt': 'วันที่ใช้',
    'coupon.scanToRedeem': 'แสดง QR Code นี้กับพนักงานเพื่อใช้คูปอง',
    
    // Login
    'login.success': 'เข้าสู่ระบบสำเร็จ',
    'login.failed': 'เข้าสู่ระบบไม่สำเร็จ',
    
    // Staff OA - Redeem Page
    'staffRedeem.title': 'ยืนยันคูปอง',
    'staffRedeem.description': 'กรอกรหัสยืนยัน 8 หลักหรือสแกน QR code ของลูกค้า',
    'staffRedeem.codeLabel': 'รหัสยืนยัน (8 หลัก)',
    'staffRedeem.codePlaceholder': '00000000',
    'staffRedeem.query': 'ค้นหา',
    'staffRedeem.querying': 'กำลังค้นหา...',
    'staffRedeem.enterCode': 'กรุณากรอกรหัสยืนยัน',
    'staffRedeem.enterCodeDesc': 'กรุณากรอกรหัสยืนยัน 8 หลัก',
    'staffRedeem.invalidFormat': 'รูปแบบรหัสไม่ถูกต้อง',
    'staffRedeem.invalidFormatDesc': 'รหัสยืนยันต้องเป็นตัวเลข 8 หลัก',
    'staffRedeem.querySuccess': 'ค้นหาคูปองสำเร็จ',
    'staffRedeem.querySuccessDesc': 'กรุณาตรวจสอบข้อมูลคูปองก่อนยืนยัน',
    'staffRedeem.queryFailed': 'ค้นหาไม่สำเร็จ',
    'staffRedeem.couponDetails': 'รายละเอียดคูปอง',
    'staffRedeem.campaignName': 'แคมเปญ',
    'staffRedeem.customerName': 'ลูกค้า',
    'staffRedeem.customerPhone': 'เบอร์โทร',
    'staffRedeem.couponValue': 'มูลค่า',
    'staffRedeem.validUntil': 'ใช้ได้ถึง',
    'staffRedeem.notes': 'หมายเหตุ',
    'staffRedeem.notesPlaceholder': 'กรอกหมายเหตุ (ถ้ามี)',
    'staffRedeem.confirmRedeem': 'ยืนยันการใช้คูปอง',
    'staffRedeem.redeeming': 'กำลังยืนยัน...',
    'staffRedeem.redeemSuccess': 'ยืนยันสำเร็จ',
    'staffRedeem.redeemSuccessDesc': 'คูปองถูกใช้งานเรียบร้อย',
    'staffRedeem.redeemFailed': 'ยืนยันไม่สำเร็จ',
    'staffRedeem.redeemAnother': 'ยืนยันคูปองถัดไป',
    'staffRedeem.loginRequired': 'จำเป็นต้องเข้าสู่ระบบ',
    'staffRedeem.loginRequiredDesc': 'กรุณาเข้าสู่ระบบด้วยบัญชีพนักงาน',
    'staffRedeem.backHome': 'กลับหน้าแรก',
    'staffRedeem.recentRedemptions': 'ประวัติการยืนยันล่าสุด',
    'staffRedeem.noPermission': 'คูปองนี้ไม่อยู่ในร้านของคุณ',
    
    // Staff OA - Stats Page
    'staffStats.title': 'สถิติการยืนยันส่วนตัว',
    'staffStats.summary': 'สรุป',
    'staffStats.today': 'วันนี้',
    'staffStats.thisWeek': 'สัปดาห์นี้',
    'staffStats.thisMonth': 'เดือนนี้',
    'staffStats.byCampaign': 'แยกตามแคมเปญ',
    'staffStats.campaignName': 'แคมเปญ',
    'staffStats.count': 'จำนวน',
    'staffStats.recentRedemptions': 'ประวัติล่าสุด',
    'staffStats.time': 'เวลา',
    'staffStats.code': 'รหัส',
    'staffStats.noData': 'ไม่มีข้อมูล',
    
    // Staff OA - Campaign Page
    'staffCampaign.title': 'แคมเปญปัจจุบัน',
    'staffCampaign.description': 'ดูข้อมูลแคมเปญที่กำลังดำเนินการ',
    'staffCampaign.activeCampaigns': 'แคมเปญที่กำลังดำเนินการ',
    'staffCampaign.campaignDetails': 'รายละเอียดแคมเปญ',
    'staffCampaign.period': 'ระยะเวลา',
    'staffCampaign.instructions': 'คำแนะนำ',
    'staffCampaign.training': 'คู่มือ',
    'staffCampaign.noCampaigns': 'ไม่มีแคมเปญที่กำลังดำเนินการ',
    
    // Dashboard - Summary
    'dashboard.title': 'แดชบอร์ด',
    'dashboard.monthSelector': 'เดือน',
    'dashboard.summary': 'สรุปรายเดือน',
    'dashboard.issuedCount': 'จำนวนออก',
    'dashboard.redeemedCount': 'จำนวนใช้',
    'dashboard.redemptionRate': 'อัตราการใช้',
    'dashboard.totalStores': 'ร้านค้าที่ใช้งาน',
    'dashboard.totalCampaigns': 'จำนวนแคมเปญ',
    'dashboard.totalBrands': 'จำนวนแบรนด์',
    'dashboard.totalClaimed': 'รับคูปองทั้งหมด',
    'dashboard.totalRedeemed': 'ใช้คูปองทั้งหมด',
    'dashboard.conversionRate': 'อัตราการใช้',
    'dashboard.campaignDimension': 'แคมเปญ',
    'dashboard.brandDimension': 'แบรนด์',
    'dashboard.storeDimension': 'ร้านค้า',
    'dashboard.campaignStats': 'สถิติแคมเปญ',
    'dashboard.brandStats': 'สถิติแบรนด์',
    'dashboard.storeStats': 'สถิติร้านค้า',
    'dashboard.campaignTitle': 'แคมเปญ',
    'dashboard.brandName': 'แบรนด์',
    'dashboard.storeName': 'ร้านค้า',
    'dashboard.storeCount': 'ร้านค้า',
    'dashboard.city': 'เมือง',
    'dashboard.noData': 'ไม่มีข้อมูล',
    
    // Dashboard - Campaigns
    'dashboard.campaigns.title': 'สถิติแยกตามแคมเปญ',
    'dashboard.campaigns.id': 'ID',
    'dashboard.campaigns.name': 'แคมเปญ',
    'dashboard.campaigns.brand': 'แบรนด์',
    'dashboard.campaigns.period': 'ระยะเวลา',
    'dashboard.campaigns.storeCount': 'ร้านค้า',
    'dashboard.campaigns.claimedCount': 'รับคูปอง',
    'dashboard.campaigns.redeemedCount': 'ใช้คูปอง',
    'dashboard.campaigns.conversionRate': 'อัตราการใช้',
    'dashboard.campaigns.noData': 'ไม่มีข้อมูลแคมเปญในเดือนนี้',
    
    // Dashboard - Brands
    'dashboard.brands.title': 'สถิติแยกตามแบรนด์',
    'dashboard.brands.name': 'แบรนด์',
    'dashboard.brands.campaignCount': 'แคมเปญ',
    'dashboard.brands.storeCount': 'ร้านค้า',
    'dashboard.brands.claimedCount': 'รับคูปอง',
    'dashboard.brands.redeemedCount': 'ใช้คูปอง',
    'dashboard.brands.conversionRate': 'อัตราการใช้เฉลี่ย',
    'dashboard.brands.noData': 'ไม่มีข้อมูลแบรนด์ในเดือนนี้',
    
    // Dashboard - Stores
    'dashboard.stores.title': 'สถิติแยกตามร้านค้า',
    'dashboard.stores.name': 'ร้านค้า',
    'dashboard.stores.brand': 'แบรนด์',
    'dashboard.stores.city': 'เมือง',
    'dashboard.stores.campaignCount': 'แคมเปญ',
    'dashboard.stores.claimedCount': 'รับคูปอง',
    'dashboard.stores.redeemedCount': 'ใช้คูปอง',
    'dashboard.stores.conversionRate': 'อัตราการใช้',
    'dashboard.stores.search': 'ค้นหาร้านค้า',
    'dashboard.stores.brandFilter': 'กรองตามแบรนด์',
    'dashboard.stores.noData': 'ไม่มีข้อมูลร้านค้าในเดือนนี้',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'zh-cn';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // 语言切换时清除所有查询缓存，确保重新获取翻译后的内容
    queryClient.invalidateQueries();
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let text = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(`{${param}}`, value);
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
